### ISSUE TITLE
receipt form api endpoints

### ISSUE THREAD

**Issue by sunb26** [sunb26/xat#128]
Receipts (Expenses)
1. Save image capture
2. Save inference result
3. Create new snapshot(s)

@Zack-Ren please add more endpoints if I missed any or new ones come up!

**Comment by Zack-Ren** [comment]
[POST] /get-receipts/{userId}?limit=X&offset=Y
(We can also use request body instead of query string)
- returns list of receipts associated with `userId`

**Comment by Lev1ty** [comment]
what about the following instead?

GET /users/{userId}/receipts?limit=X&offset=Y

**Comment by Zack-Ren** [comment]
Yeah that works, I like that.

**Comment by Zack-Ren** [comment]
If we want to include a searching feature where we can filter by a search parameter and query, we could use POST and pass the search parameters in the body. For now, what @Lev1ty mentioned in 4 above is sufficient imo.
