### ISSUE TITLE
verify file id endpoint

### ISSUE THREAD

**Issue by sunb26** [sunb26/xat#295]
verify the file id of the google drive link with gdrive api

**Comment by sunb26** [comment]
Implementation Clarification:

- this is not a separate endpoint, this is incorporated into the create_scan_inference endpoint (will be renamed if we go through wit this)
- The endpoint will receive the image url and the file id to verify the file id matches the url permissions
- if matches - proceed if not return error

**Comment by Lev1ty** [comment]
The endpoint only needs to receive the file id. With the file id, we can call the google drive api. Also I'm not sure if it should go into the create scan inference endpoint. Would it be more suitable to go into some endpoint for storing image urls? Unless that is what create scan inference endpoint does

**Comment by sunb26** [comment]
Exploring email option
