### ISSUE TITLE
figure out the initial db schema

### ISSUE THREAD

**Issue by sunb26** [sunb26/xat#67]

**Comment by sunb26** [comment]
User table
1. UserName
2. JoinDate

Scans table (images of receipts and invoices)
1. ScanId
2. UserName
3. ScanType
4. Image


Scan_Results table (parent  = scan, the ocr results of each scan)
1. ResultId
2. ScanId
3. Result

**Comment by Lev1ty** [comment]
* join_date may be misleading as there is a sql operator called join, try using more canonical names such as create_date, or document these lifecycle states and associated metadata like dates
* decide on a consistent casing style, either PascalCase, snake_case or camelCase
* please explain how these tables relate to each other, including foreign key constraints

**Comment by sunb26** [comment]
^^ updated comment above to reflect suggestions

**Comment by Lev1ty** [comment]
Why not merge scan and scan result if they are one-to-one? Maybe use create_time instead of create_date. Also, prefer id over name as former is more common in databases. I'm sure you're working on how these tables relate to the business data tables like expense and revenue tables. Do we also want to have a revisions table tracking modifications made to expenses and revenues, like corrections and overrides from amounts that come from scanning and inference

**Comment by sunb26** [comment]
yeah sure we can have a modifications table. I've updated the comment above again with what I think should suffice as the current schema - let me know if I'm missing anything @Lev1ty  @Zack-Ren

**Comment by sunb26** [comment]
^^ updated schema again @Lev1ty - let me know if you have any suggestions/comments

**Comment by Lev1ty** [comment]
could you pull this into a google doc for easier collaboration and inline comments

**Comment by Lev1ty** [comment]
projects might be pretty worthwhile here. example user is part of their business (an organization) and creates a project for this year's returns, and another project for next years. we can have some synergies to carry over information from this year's returns to next year

**Comment by sunb26** [comment]
https://docs.google.com/document/d/1YX4zu_Rp4z0pcFkkbXnr3kvwwCmdIK4Esx7qRUEk4c4/edit?usp=sharing

**Comment by sunb26** [comment]
What fields would be relevant to projects?

**Comment by Lev1ty** [comment]
I think everything we associated with use before, now we associate it with project. And then a user can have/manage many projects
