### ISSUE TITLE
image storage

### ISSUE THREAD

**Issue by sunb26** [sunb26/xat#89]
- compress and store as a blob/bytearray in sql databse
- store filepath in sql database and store actual image in file system elsewhere

discuss at next meeting

**Comment by Lev1ty** [comment]
i guess a point of news i would like to point out is that planetscale discontinued their free tier, so storage capacity is now a limiting concern based on neondb's pricing scheme

still i would like to know size of impact here, as in how large do we expect the images to be. we could even do a migration to blob storage when the storage size in database gets unmanageable with scale, and start off with db only to reduce initial complexity

**Comment by sunb26** [comment]
Decision - store images on GD and store url in Neon
