### ISSUE TITLE
fix bazel atlas cli apply

### ISSUE THREAD

**Issue by sunb26** [sunb26/xat#96]
command typo - should be 

$ATLAS schema apply --url $$DSN --to \"file://$SCHEMA\" --dry-run

$$DSN is not being recognized properly for some reason. 

![image](https://github.com/sunb26/xat/assets/56877739/414268a3-9654-4bcf-bcf8-5696eb6f0993)

Inspect command works fine.

@Lev1ty

**Comment by sunb26** [comment]
the boxed area is just an echo of the command that should be executed

**Comment by Lev1ty** [comment]
suggest you rotate the database secrets as you sent a screenshot that contains the cleartext DSN

**Comment by sunb26** [comment]
![image](https://github.com/sunb26/xat/assets/56877739/9725a2ff-6275-4e77-b0c2-c5734940ab15)

The apply command still doesn't work - it doesn't find the DSN it seems.
